config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :titles

  root 'titles#home'

  get 'titles/home'
  get 'titles/index'
  get 'titles/about'
  get 'titles/help'

  get '/home',    to: 'titles#home'
  get '/index',   to: 'titles#index'
  get '/about',   to: 'titles#about'
  get '/help',    to: 'titles#help'

  post '/home',   to: 'titles#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/title.rb
class Title < ApplicationRecord

  before_save   :downcase_email

  validates :uri, presence: true, length: { maximum: 150 },
                  uniqueness:
                    { case_sensitive: false, message: " has already been searched" }
                    #{ case_sensitive: false, message: "%{attribute} is duplicated" }
                    #{ case_sensitive: false, message: ->(object, data) do "Hey #{object.uri}!, #{data[:value]} is taken already!" end }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :email, presence:   true, length: { maximum: 150 },
                    format:     { with: VALID_EMAIL_REGEX }

  # Sends search result email.
  def send_result_email
    TitleMailer.send_result(self).deliver_now
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      email.downcase!
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  def hello
    render html: "Hi, welcome on Title & location!"
  end

end

app/controllers/title_location_controller.rb
require 'mechanize'

class TitleLocationController < ApplicationController

  def home
  #  @title = Title.first
    @title = Title.new
    @mechanize = Mechanize.new
    @page1 = @mechanize.get('https://www.seznam.cz/')
    @mechanize = Mechanize.new
    @page2 = @mechanize.get('https://edition.cnn.com/')
    @mechanize = Mechanize.new
    @page3 = @mechanize.get('https://www.weather-forecast.com/')
  end

  def about
  end

  def submit
  end

  def help
  end

end

app/controllers/titles_controller.rb
require 'mechanize'
require 'socket'

class TitlesController < ApplicationController

  # --- HOME ---

  def home
    
#    if !@title.nil?
#      puts "Errors count_c: " + @title.errors.count.to_s
#    end
#    if @title.nil?
#      @title = Title.new
#    else
#      debugger      
#    end
#    puts "Errors count_d: " + @title.errors.count.to_s
    
    @title = Title.new
    @titles = Title.all.order("created_at DESC")

#    if @title.nil?
#      @title = Title.new
#    end

#    if @title_err.nil?
#      @title = Title.new
#    else
#      @title = @title_err
#    end

  end

  def index
    @titles = Title.all.order("created_at DESC").paginate(page: params[:page])
  end

  # --- ABOUT ---

  def about
  end

  # --- HELP ---

  def help
  end

  # --- CREATE ---

  def create

    @title = Title.new(title_params)
    @mechanize = Mechanize.new
    
    @uri_ok = false
    @uri_ok = @title.uri.downcase.include? "https://"
    if !@uri_ok
      @uri_ok = @title.uri.downcase.include? "http://"
    end

    #debugger

    if !@uri_ok
      
      begin
        @mechanize_page = @mechanize.get('https://' + @title.uri)
      rescue => e
        @mechanize_page = nil
        p e
      end      

      #debugger

      if @mechanize_page.nil?

        begin
          @mechanize_page = @mechanize.get('http://' + @title.uri)
        rescue => e
          @mechanize_page = nil
          p e
        end      

      end

    else
      
      begin
        @mechanize_page = @mechanize.get(@title.uri)
      rescue => e
        @mechanize_page = nil
        p e
      end      

    end
    
    #debugger

    if @mechanize_page.nil?
      @title.errors.add(:base, "Invalid URL")
    end

    #debugger

    if @title.errors.count == 0
      @ip_address = IPSocket::getaddress(@mechanize_page.uri.host)
      @result_geo = Geocoder.search(@ip_address)
      @title.uri = @mechanize_page.uri.host.to_s
#      @title.uri = @mechanize_page.uri.to_s
      @title.title = @mechanize_page.title
      @title.location = @result_geo.first.address + ", " + @result_geo.first.region
      if verify_recaptcha(model: @title) && @title.save
      #if @title.save
        @title.send_result_email
        flash[:info] = "Please check your email for requested details."
        redirect_to root_url
      else
# zde by mozna byla moznost najit chybu(chyby) URI a zmenit ji na URL
        #@title_err = @title
        #debugger
#        puts "Errors count (A): " + @title.errors.count.to_s
#        puts "Errors list (A): " + @title.errors.full_messages.to_s
        @titles = Title.all.order("created_at DESC")
        render 'home'
      end
    else
#        puts "Errors count (B): " + @title.errors.count.to_s
#        puts "Errors list (B): " + @title.errors.full_messages.to_s
        @titles = Title.all.order("created_at DESC")
        render 'home'
    end

  end

  # --- SHOW ---

  def show
    @title = Title.find(params[:id])
  end

  #def new
  #  @title = Title.new
  #  render 'home'
  #end

  def destroy
    Title.find(params[:id]).destroy
    flash[:success] = "Row deleted"
    #redirect_to index_url
    redirect_to root_url
  end

  private

    def title_params
#      params.require(:title).permit(:uri, :email, :title, :location)
      params.require(:title).permit(:uri, :email)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title.
  def full_title(page_title = '')
    base_title = "Title and Location Request App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/title_location_helper.rb
module TitleLocationHelper
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.seznam.cz/">Seznam</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<head>

  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>

</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Titles and Locations", root_path, id: "logo" %>
    <nav>
      <ul id="menutop" class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Index", index_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Help", help_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

  <%= render 'layouts/head' %>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>      
    </div>
  </body>

</html>

app/views/shared/_error_messages.html.erb
  <% puts "Errors count (err-msg): " + @title.errors.count.to_s %>
  <% puts "Errors list (err-msg): " + @title.errors.full_messages.to_s %>
  <% puts "Errors any (err-msg): " + @title.errors.any?.to_s %>

  <% if @title.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        Please correct following <%= pluralize(@title.errors.count, "error") %>:
      </div>
      <ul>
      <% @title.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% @title.errors.full_messages.each do |error| %>
      <li><%= error %></li>
  <% end %>

app/views/title_location/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<h1>Title & Location - <%= yield(:title) %></h1>
<h2>
  Welcome to the About page of Title and Location Request App.
</h2>

app/views/title_location/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<h1>Title & Location - <%= yield(:title) %></h1>
<h2>
  Welcome to the Help page of Title and Location Request App.
</h2>

app/views/title_location/home.html.erb
<!--
<div class="center jumbotron">

  <h1>Welcome to the Title & Location App</h1>

  <h2>
    This is the home page for the customer Title and Location request page.
  </h2>

</div>

<hr/>
-->

<div class="table jumbotron">

  <div class="row">
  
    <div class="col-md-4 col-md-offset-2">
  
      <%= form_with model: @title do |f| %>
        
        <%= f.label :uri %>
        <%= f.text_field :uri, class: 'form-control' %>
  
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
  
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
  
        <%= f.submit "Request details", class: "btn btn-primary" %>
      <% end %>
  
    </div>
  
  </div>

</div>

<hr/>

<div class="jumbotron">

  <div class="row">
    <div class="col-md-6 col-md-offset-2">
      <u>Titles of 4 static pages:</u><br/><br/>
    </div>
  </div>

  <div class="row">
    <div class="col-md-1 col-md-offset-2">
      Site 
    </div>
    <div class="col-md-3">
      Uri 
    </div>
    <div class="col-md-6">
      Title 
    </div>
  </div>

  <div class="row">
    <div class="col-md-1 col-md-offset-2">
      Seznam: 
    </div>
    <div class="col-md-3">
      <%= @page1.uri %> 
    </div>
    <div class="col-md-6">
      <%= @page1.title %> 
    </div>
  </div>

  <div class="row">
    <div class="col-md-1 col-md-offset-2">
      CNN: 
    </div>
    <div class="col-md-3">
      <%= @page2.uri %> 
    </div>
    <div class="col-md-6">
      <%= @page2.title %> 
    </div>
  </div>

  <div class="row">
    <div class="col-md-1 col-md-offset-2">
      Weather: 
    </div>
    <div class="col-md-3">
      <%= @page3.uri %> 
    </div>
    <div class="col-md-6">
      <%= @page3.title %> 
    </div>
  </div>

</div>

app/views/title_location/submit.html.erb
<h1>TitleLocation#submit</h1>
<p>Find me in app/views/title_location/submit.html.erb</p>

app/views/titles/_title.html.erb
<div class="row" style="margin-bottom: 10px;">

  <div class="col-md-2">
    <%= title.created_at.strftime("%F %H:%M") %>
  </div>

  <div class="col-md-2">
    <%= title.uri %>
  </div>

  <div class="col-md-2">
    <%= title.email %>
  </div>

  <div class="col-md-3">
    <%= title.title %>
  </div>

  <div class="col-md-2">
    <%= title.location %>
  </div>

  <div class="col-md-1">
    <%= link_to "delete", title, method: :delete, data: { confirm: "Do you realy want to delete selected row?" } %>
  </div>

</div>

app/views/titles/_title_form.erb
      <%= form_for @title do |f| %>

        <% if @title.errors.any? %>

        <div class="row">
          <div class="col-md-11">
            <div id="error_explanation">
              <div class="alert alert-danger">
                Please correct following <%= pluralize(@title.errors.count, "error") %>:
              </div>
              <ul>
              <% @title.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          </div>
        </div>

          <%# render 'shared/error_messages' %>
        <% end %>
        
        <div class="row">
        
          <div class="col-md-6">
<!--            < %= f.label :Url %>: -->
            <%= f.label :uri %>
          </div>

          <div class="col-md-6">
            <%= f.label :email %>
          </div>

        </div>

        <div class="row">
        
          <div class="col-md-6">
            <%= f.text_field :uri, class: 'form-control input-sm' %>
          </div>

          <div class="col-md-6">
            <%= f.email_field :email, class: 'form-control input-sm' %>
          </div>

        </div>

        <div class="row">
        
          <div class="col-md-6" style="border: 0px solid lightblue;">
            <!-- <div class="g-recaptcha" data-sitekey="6LfU0qwUAAAAAKd0cs_tT4w0iQShXjrhE8OnqXVg"> -->
              <%= recaptcha_tags %>
            <!-- </div> -->
          </div>

          <div class="col-md-6 d-flex align-items-center">
            <%= f.submit "Search for details", class: "btn btn-md btn-primary" %>
          </div>

        </div>

      <% end %>

app/views/titles/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<h1>Titles & Locations - <%= yield(:title) %></h1>
<p>
  This is the Titles & Locations Application developed in July 2019.
</p>

app/views/titles/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<h1>Titles & Locations - <%= yield(:title) %></h1>
<p>
  This is the Help page for the Titles & Locations Application.
</p>

<p>
  <u>How to enter a URL value</u><br/>
  You can enter a URL value either by its relative form, like www.google.com<br/>
  or by its absolute form, like https://www.google.com (for secure connection) or http://www.google.com (for not secure connection).
</p>

app/views/titles/home.html.erb
<div class="table jumbotron" id="table_01">

  <div class="row">
    
    <div class="col-md-6" style="border: 0px solid blue;">
      <h2>Welcome on the Titles & Locations searching page.</h2><br/>
      1. Enter the Url of requested site. See help link for some advice.<br/>
      2. Enter your email address where the searched result will be sent to.<br/>
      3. Tick the reCaptcha to confirm you are not a robot.<br/>
      4. Click the <b>Search for details</b> button.
    </div>

    <div class="col-md-6" style="border: 0px solid blue;">
      <%= render 'title_form' %>
    </div>

  </div>

</div>

<div class="table jumbotron" id="table_02">

  <div class="row">
    <div class="col-md-12">
      <h2>Search history:</h2u>
    </div>
  </div>

  <hr/>
  
  <div class="row" style="margin-bottom: 10px;">
  
    <div class="col-md-2">
      <b>Date</b>
    </div>
  
    <div class="col-md-2">
      <b>Url</b>
    </div>
  
    <div class="col-md-2">
      <b>Email</b>
    </div>
  
    <div class="col-md-3">
      <b>Title</b>
    </div>
  
    <div class="col-md-3">
      <b>Location</b>
    </div>
  
  </div>
  
  <%= render @titles %>
  
  <hr/>
  
</div>

app/views/titles/index.html.erb
<% provide(:title, 'All titles') %>

<h1>Titles & Locations - List</h1>

<%= will_paginate %>

<hr/>

<div class="row" style="margin-bottom: 10px;">

  <div class="col-md-2">
    <b>Date</b>
  </div>

  <div class="col-md-2">
    <b>Url</b>
  </div>

  <div class="col-md-2">
    <b>Email</b>
  </div>

  <div class="col-md-3">
    <b>Title</b>
  </div>

  <div class="col-md-3">
    <b>Location</b>
  </div>

</div>

<%= render @titles %>

<hr/>

<%= will_paginate %>

app/views/titles/new.html.erb
<h1>Titles#new</h1>
<p>Find me in app/views/titles/new.html.erb</p>

app/views/titles/show.html.erb
<h1>Title details</h1>

id: <%= @title.id %><br/>
url: <%= @title.uri %><br/>
email: <%= @title.email %><br/>
title: <%= @title.title %><br/>
location: <%= @title.location %><br/>
created: <%= @title.created_at %><br/>